// ==========================================
// MASTER QUESTION BANK (APUSH & AP ENGLISH)
// Format: [Unit/Period, "Question Text", "Correct Answer", "Wrong 1", "Wrong 2", "Wrong 3"]
// ==========================================

const apushBank = [
  // --- PERIOD 1 (1491-1607) ---
  [1,"How did the cultivation of maize primarily impact pre-Columbian Native American societies?","It supported economic development, settlement, and social diversification.","It led to rapid desertification of the Great Plains.","It forced indigenous populations to adopt nomadic lifestyles.","It prevented the establishment of large trade networks."],
  [1,"What was the primary goal of the Spanish encomienda system?","To extract labor from Native Americans while ostensibly converting them to Christianity.","To establish equal trade alliances with the Aztec Empire.","To grant sovereign land rights to indigenous leaders.","To completely replace Native laborers with indentured Europeans."],
  [1,"How did Native Americans in the Great Basin and western Plains primarily adapt to their environment?","By developing highly mobile, nomadic lifestyles focused on hunting.","By constructing massive irrigation networks for intensive farming.","By establishing permanent, multi-story cliff dwellings.","By relying exclusively on fishing and whaling economies."],
  [1,"Which factor was most responsible for the drastic decline of Native American populations after 1492?","The introduction of Eurasian diseases like smallpox to which they had no immunity.","Protracted military conflicts with English settlers.","Widespread famine caused by European agricultural practices.","The mass migration of indigenous peoples to South America."],
  [1,"What was the central argument of Bartolomé de las Casas regarding Spanish colonization?","He strongly condemned the brutal treatment of Native Americans.","He argued that the encomienda system was divinely ordained.","He advocated for the immediate enslavement of all indigenous peoples.","He believed Native Americans should be forced off their ancestral lands."],
  
  // --- PERIOD 2 (1607-1754) ---
  [2,"What was the primary economic motivation for the founding of Jamestown?","To generate profits for the investors of the Virginia Company.","To establish a religious haven for persecuted Puritans.","To create an egalitarian society based on subsistence farming.","To build a strategic military base against the French."],
  [2,"How did the development of tobacco cultivation affect the Chesapeake colonies?","It created a heavy reliance on indentured servitude and later African slavery.","It led to the rapid development of large, bustling urban centers.","It promoted peaceful and cooperative relations with the Powhatan.","It encouraged the establishment of public schools and universities."],
  [2,"Which of the following was a key characteristic of the New England colonies?","They were settled by families seeking religious freedom and built tight-knit communities.","They relied primarily on the cultivation of cash crops like rice and indigo.","They featured a highly unequal society dominated by a small planter elite.","They actively encouraged the immigration of diverse religious groups like Catholics."],
  [2,"What was the primary cause of Bacon's Rebellion in 1676?","Frustration of poor backcountry farmers over the governor's Native American policies.","A dispute over the enforcement of the British Navigation Acts.","Religious tension between Anglicans and dissenting Puritans.","A slave uprising aimed at ending the plantation system in Virginia."],
  [2,"The Middle Colonies (New York, Pennsylvania) were distinct because they:","Featured demographic, religious, and ethnic diversity with a thriving export economy.","Relied almost entirely on enslaved African labor for tobacco farming.","Maintained strict religious conformity governed by Puritan theology.","Were entirely neglected by the British government until the 1750s."],

  // --- PERIOD 3 (1754-1800) ---
  [3,"What was the primary consequence of the French and Indian War for Great Britain?","It left Britain with massive debt, leading to new taxes on the colonies.","It resulted in the immediate loss of all British territory in North America.","It ushered in an era of unprecedented political autonomy for the colonies.","It caused the British Parliament to abolish the mercantilist system."],
  [3,"The Proclamation of 1763 angered American colonists because it:","Banned colonial settlement west of the Appalachian Mountains.","Imposed a direct tax on all printed materials in the colonies.","Required colonists to provide housing and food for British troops.","Granted a monopoly on the tea trade to the East India Company."],
  [3,"What was the main argument of the colonists against the Stamp Act?","Only their elected colonial assemblies had the right to tax them directly.","The tax rate was too high for the average farmer to afford.","The revenue was being used to fund wars in Europe rather than America.","It violated their right to freely trade with the French West Indies."],
  [3,"Thomas Paine’s 'Common Sense' was highly influential because it:","Used clear, persuasive language to argue for independence and a republic.","Detailed a comprehensive military strategy for defeating the British army.","Proposed a specific framework for the United States Constitution.","Argued that the colonies should seek reconciliation with King George III."],
  [3,"Which Enlightenment thinker's ideas about natural rights heavily influenced the Declaration of Independence?","John Locke","Thomas Hobbes","Jean-Jacques Rousseau","Voltaire"],

  // --- PERIOD 4 (1800-1848) ---
  [4,"What was the significance of the Supreme Court ruling in Marbury v. Madison (1803)?","It established the principle of judicial review over federal laws.","It upheld the constitutionality of the National Bank.","It declared that states could not tax federal institutions.","It ruled that Native American tribes were sovereign nations."],
  [4,"Why was Thomas Jefferson initially hesitant to authorize the Louisiana Purchase?","The Constitution did not explicitly grant the president power to purchase land.","He feared it would upset relations with the British Empire.","He believed the land was too vast and uninhabitable for farming.","He thought it would accelerate the industrialization of the United States."],
  [4,"The Market Revolution of the early 19th century was characterized by:","The shift toward commercial agriculture and specialized industrial production.","A decline in urbanization as people moved to frontier farms.","The complete eradication of the institution of slavery.","A return to self-sufficient, localized barter economies."],
  [4,"Which of the following was a major effect of the construction of the Erie Canal?","It dramatically lowered the cost of shipping goods between the Midwest and the East Coast.","It caused the economic decline of New York City in favor of New Orleans.","It completely eliminated the need for railroad construction in the North.","It directly led to the outbreak of the War of 1812."],
  [4,"The primary objective of the Monroe Doctrine was to:","Prevent European powers from establishing new colonies in the Western Hemisphere.","Assert the right of the United States to expand into Canada and Mexico.","Form a permanent military alliance with Great Britain against France.","Justify the forced removal of Native Americans from the Southeast."],

  // --- PERIOD 5 (1844-1877) ---
  [5,"The ideology of Manifest Destiny was used to justify:","The westward expansion of the US to the Pacific Ocean.","The strict containment of slavery to the South.","The immediate assimilation of Native Americans.","The establishment of an overseas American empire."],
  [5,"Which event directly sparked the Mexican-American War?","A dispute over the southern boundary of Texas.","The Mexican attack on the Alamo.","The publication of the Ostend Manifesto.","The US annexation of California."],
  [5,"The Wilmot Proviso controversially proposed that:","Slavery be banned in any territory acquired from Mexico.","California be admitted as a slave state.","The Missouri Compromise line be extended to the Pacific.","Popular sovereignty decide the fate of all new territories."],
  [5,"A major component of the Compromise of 1850 that outraged Northerners was the:","Passage of a much stricter Fugitive Slave Act.","Abolition of the slave trade in Washington D.C.","Admission of California as a free state.","Implementation of popular sovereignty in Utah and New Mexico."],
  [5,"Uncle Tom's Cabin heavily influenced public opinion by:","Personalizing the brutal reality of slavery for Northern readers.","Providing a historical defense of the plantation system.","Arguing for the immediate colonization of freedmen in Africa.","Exposing the political corruption of the Buchanan administration."],

  // --- PERIOD 6 (1865-1898) ---
  [6,"The completion of the Transcontinental Railroad in 1869 had which major economic impact?","It integrated national markets and spurred rapid industrial and western development.","It immediately collapsed the agricultural economy of the Midwest.","It ended the era of massive European immigration to the East Coast.","It caused a drastic decline in the profitability of the steel industry."],
  [6,"What was the primary purpose of the Homestead Act of 1862?","To encourage western settlement by offering 160 acres of free land to farmers.","To provide land grants for the construction of transcontinental railroads.","To establish reservations for Native American tribes displaced by white settlers.","To allocate federal lands for the creation of agricultural colleges."],
  [6,"The Dawes Severalty Act of 1887 was an attempt to assimilate Native Americans by:","Breaking up tribal reservations into individual farming plots.","Sending Native American children to federally funded boarding schools.","Granting full US citizenship to all Native Americans.","Encouraging the preservation of traditional indigenous religions like the Ghost Dance."],
  [6,"Andrew Carnegie's concept of the 'Gospel of Wealth' argued that:","The wealthy had a moral obligation to use their fortunes for the public good.","Unfettered capitalism was a sin against Christian teachings.","The government should heavily tax the rich to distribute wealth evenly.","Labor unions were essential to maintaining a fair and moral economy."],
  [6,"During the Gilded Age, the theory of Social Darwinism was frequently used to:","Justify extreme wealth inequality and unregulated laissez-faire capitalism.","Argue for extensive government regulation of monopolies.","Promote social welfare programs for the urban poor.","Support the rights of workers to collectively bargain."],

  // --- PERIOD 7 (1890-1945) ---
  [7,"Muckrakers like Upton Sinclair and Ida Tarbell were journalists who:","Exposed political corruption and corporate abuses to spark public reform.","Wrote sensationalist yellow journalism to start the Spanish-American War.","Promoted the extreme laissez-faire economic policies of the Gilded Age.","Defended the actions of political machines like Tammany Hall."],
  [7,"Which of the following was a primary motivation for American imperialism in the 1890s?","The desire for new overseas markets and naval coaling stations.","A need to acquire new land for mass European immigration.","The goal of spreading democratic institutions to the nations of Europe.","A commitment to upholding the Monroe Doctrine globally."],
  [7,"The Spanish-American War resulted in the United States acquiring which territories?","The Philippines, Puerto Rico, and Guam.","Cuba, Hawaii, and Alaska.","The Dominican Republic, Haiti, and the Virgin Islands.","Panama, Nicaragua, and Mexico."],
  [7,"The Roosevelt Corollary to the Monroe Doctrine stated that the US had the right to:","Intervene militarily in Latin American nations to maintain order and collect debts.","Annex any territory in the Western Hemisphere by force.","Prevent any Asian immigration into the United States.","Establish free trade agreements across all of South America."],
  [7,"Which event was the immediate catalyst for the United States entering World War I?","The interception of the Zimmermann Telegram and unrestricted submarine warfare.","The assassination of Archduke Franz Ferdinand.","The sinking of the RMS Lusitania in 1915.","The Russian Bolshevik Revolution."],

  // --- PERIOD 8 (1945-1980) ---
  [8,"The Truman Doctrine established the US foreign policy of:","Containment, committing to support free peoples resisting communist subjugation.","Massive retaliation, threatening nuclear war against any Soviet aggression.","Détente, seeking peaceful coexistence and arms reduction with the USSR.","Isolationism, withdrawing all American troops from Europe."],
  [8,"The Marshall Plan aimed to prevent the spread of communism by:","Providing massive economic aid to rebuild the devastated economies of Western Europe.","Forming a mutual defense pact with democratic nations (NATO).","Engaging in a massive buildup of conventional military forces.","Dropping supplies into blockaded cities, as seen in Berlin."],
  [8,"The Second Red Scare and McCarthyism were characterized by:","Aggressive, often unsubstantiated accusations of communist infiltration in the US government.","A highly successful effort to uncover hundreds of actual Soviet spies.","The complete outlawing of the Democratic Party.","A focus entirely on exposing communists in the Hollywood film industry."],
  [8,"The Supreme Court's landmark decision in Brown v. Board of Education (1954) ruled that:","Racial segregation in public schools was inherently unequal and unconstitutional.","The 'separate but equal' doctrine applied only to elementary schools.","Busing was an illegal method for achieving school integration.","The federal government could not interfere with state education policies."],
  [8,"Martin Luther King Jr.'s strategy for achieving civil rights relied primarily on:","Nonviolent civil disobedience and peaceful mass protests.","Armed self-defense and black nationalism.","Lengthy legal battles in federal courts exclusively.","The gradual accommodation of Jim Crow laws."],

  // --- PERIOD 9 (1980-Present) ---
  [9,"The 'Reagan Revolution' of the 1980s was characterized by a conservative agenda that emphasized:","Tax cuts, deregulation of business, and a massive increase in military spending.","The rapid expansion of federal welfare programs.","A policy of strict détente and arms reduction with the Soviet Union.","The nationalization of major industries and banks."],
  [9,"What was a major consequence of the Persian Gulf War (1991)?","A successful US-led coalition expelled Iraqi forces from Kuwait.","Saddam Hussein was immediately removed from power and executed.","The US permanently annexed the oil fields of the Middle East.","The United Nations was dissolved due to its failure to act."],
  [9,"The North American Free Trade Agreement (NAFTA), signed in 1993, aimed to:","Eliminate trade barriers between the US, Canada, and Mexico.","Create a single currency for the Western Hemisphere.","Prevent the outsourcing of American manufacturing jobs.","Establish a mutual defense pact against European aggression."],
  [9,"How did US foreign policy drastically shift following the September 11, 2001 terrorist attacks?","The US launched a global 'War on Terror,' leading to invasions of Afghanistan and Iraq.","The US retreated into strict isolationism to protect the homeland.","The US formed a permanent military alliance with the Russian Federation.","The US immediately withdrew all military forces from the Middle East."],
  [9,"The Great Recession of 2008 was triggered primarily by the collapse of the:","Housing market due to risky subprime mortgage lending.","Tech industry following the burst of the dot-com bubble.","Global oil supply due to conflicts in the Middle East.","American automotive industry's manufacturing base."]
];

// ==========================================
// AP ENGLISH LANGUAGE & LITERATURE BANK
// ==========================================
const englishBank = [
  // --- Unit 1: Rhetorical Strategies & Terms ---
  [1, "In rhetoric, what is the primary function of 'anaphora'?", "To emphasize a point through the repetition of a word or phrase at the beginning of successive clauses.", "To contrast two opposing ideas in parallel grammatical structures.", "To appeal to the audience's sense of logic and deductive reasoning.", "To intentionally downplay the significance of a major event."],
  [1, "Which literary device involves a seemingly self-contradictory statement that may nonetheless reveal a hidden truth?", "Paradox", "Oxymoron", "Synecdoche", "Hyperbole"],
  [1, "What is the defining characteristic of an 'epistolary' novel?", "It is written as a series of documents or letters.", "It features a non-linear narrative focusing on stream of consciousness.", "It is written entirely in unrhymed iambic pentameter.", "It heavily relies on the intervention of mythological gods."],
  [1, "A writer using 'pathos' is primarily attempting to appeal to the audience's:", "Emotions and sympathies.", "Sense of logic and objective facts.", "Trust in the author's credibility and moral character.", "Understanding of historical precedents."],
  [1, "In literature, a 'bildungsroman' focuses on what specific narrative arc?", "The psychological and moral growth of the protagonist from youth to adulthood.", "A tragic hero whose fatal flaw inevitably leads to their downfall.", "A comedic satire criticizing the social elite of a specific era.", "A dystopian future where society is controlled by an authoritarian regime."],
  [1, "The term 'syntax' in literary analysis primarily refers to:", "The arrangement of words and phrases to create well-formed sentences.", "The author's specific choice of vocabulary and diction.", "The underlying emotional tone or mood of the passage.", "The explicit thesis or main argument of a persuasive essay."],
  [1, "When an author replaces the name of a thing with the name of something else with which it is closely associated (e.g., 'The Crown' for the King), it is called:", "Metonymy", "Simile", "Personification", "Alliteration"],
  [1, "Which of the following best defines a 'straw man' logical fallacy?", "Misrepresenting an opponent's argument to make it easier to attack.", "Attacking the opponent's character instead of their argument.", "Assuming that because one event follows another, the first caused the second.", "Arguing that a claim must be true because a majority of people believe it."],
  [1, "What is the rhetorical purpose of a 'litotes'?", "To emphasize a point by using an understatement, usually involving a double negative.", "To heavily exaggerate a situation for comedic effect.", "To compare two unrelated objects using the words 'like' or 'as'.", "To pose a question to the audience without expecting an actual answer."],
  [1, "A narrative that contains a secondary, hidden meaning (often moral or political) beneath the surface story is known as an:", "Allegory", "Anecdote", "Elegy", "Ode"],
  
  // --- Unit 2: Poetry & Devices ---
  [2, "What is the defining structure of an English (Shakespearean) sonnet?", "Three quatrains followed by a rhyming couplet (ABAB CDCD EFEF GG).", "An octave followed by a sestet (ABBAABBA CDECDE).", "Five tercets followed by a quatrain, with repeating end words.", "Fourteen lines of unrhymed iambic pentameter (blank verse)."],
  [2, "The phrase 'the murmuring of innumerable bees' relies primarily on which poetic device to mimic its subject?", "Onomatopoeia", "Assonance", "Consonance", "Enjambment"],
  [2, "In poetry, what does 'enjambment' refer to?", "The continuation of a sentence without a pause beyond the end of a line or stanza.", "A sudden, hard pause in the middle of a line of verse.", "The repetition of internal vowel sounds within closely grouped words.", "A strict adherence to a specific meter and rhyme scheme."],
  [2, "What is the primary characteristic of 'blank verse'?", "It consists of unrhymed lines in iambic pentameter.", "It has no set meter and no set rhyme scheme.", "It consists entirely of rhyming couplets.", "It is a poem written in the shape of its subject matter."],
  [2, "A poem that laments the dead or reflects on human mortality is known as an:", "Elegy", "Ode", "Epic", "Ballad"],
  [2, "The use of the word 'white' to describe a bride's dress, symbolizing purity and innocence, is an example of:", "Connotation", "Denotation", "Juxtaposition", "Satire"],
  [2, "Which meter is used in the line 'To be or not to be, that is the question'?", "Iambic Pentameter", "Trochaic Tetrameter", "Dactylic Hexameter", "Anapestic Dimeter"],
  [2, "A 'volta' in poetry refers to:", "The turn of thought or argument, typically found in sonnets.", "The repeated chorus at the end of every stanza.", "The final, concluding syllable of a rhymed line.", "The specific emotional tone established in the first line."],
  [2, "When a poet directly addresses an absent person, an abstract concept, or an inanimate object, they are using:", "Apostrophe", "Euphemism", "Chiasmus", "Zeugma"],
  [2, "The poetic device of 'assonance' is best defined as:", "The repetition of identical or similar vowel sounds in neighboring words.", "The repetition of initial consonant sounds across multiple words.", "The direct comparison of two seemingly unlike things.", "The use of harsh, discordant sounds to create an unsettling effect."],

  // --- Unit 3: American Literature (Foundations to 1900) ---
  [3, "Which movement in American literature heavily emphasized individualism, intuition, and the inherent goodness of nature?", "Transcendentalism", "Naturalism", "Realism", "Modernism"],
  [3, "Nathaniel Hawthorne and Edgar Allan Poe are primarily associated with which literary subgenre?", "Dark Romanticism", "The Harlem Renaissance", "Puritan Plain Style", "Regionalism"],
  [3, "Mark Twain's 'The Adventures of Huckleberry Finn' is a classic example of American Regionalism due to its:", "Extensive use of local dialects, geography, and social customs.", "Focus on wealthy, aristocratic elites in New England society.", "Strict adherence to traditional, formal British grammatical structures.", "Exploration of the psychological impact of the Industrial Revolution."],
  [3, "Which American poet is famous for breaking traditional rules of meter and using free verse in 'Leaves of Grass'?", "Walt Whitman", "Emily Dickinson", "Robert Frost", "Henry Wadsworth Longfellow"],
  [3, "The literary movement of 'Realism' emerged after the Civil War primarily as a reaction against:", "The idealized, highly emotional depictions of Romanticism.", "The bleak, deterministic worldview of Naturalism.", "The experimental, fragmented narratives of Modernism.", "The strict religious moralizing of early Colonial literature."],

  // --- Unit 4: British Literature (Classics to 1900) ---
  [4, "In William Shakespeare's 'Macbeth', what is the protagonist's 'hamartia' (tragic flaw)?", "His unchecked, vaulting ambition.", "His immense cowardice in battle.", "His naive trust in his political rivals.", "His excessive love for his children."],
  [4, "Which literary period is characterized by a focus on reason, logic, scientific inquiry, and a return to classical forms?", "The Enlightenment (Neoclassicism)", "The Romantic Period", "The Victorian Era", "The Renaissance"],
  [4, "Mary Shelley's 'Frankenstein' is considered a foundational text of which literary genre?", "Gothic Fiction", "Historical Fiction", "Utopian Literature", "Satirical Comedy"],
  [4, "The Victorian era of literature often focused heavily on:", "Social critique, class struggles, and the impact of the Industrial Revolution.", "The celebration of untamed nature and the rejection of all social norms.", "Highly fragmented narratives and the unreliability of language.", "The absolute divine right of monarchs and strict religious adherence."],
  [4, "Geoffrey Chaucer's 'The Canterbury Tales' is significant in literary history primarily because it:", "Popularized the use of the English vernacular in literature.", "Was the first novel ever published on a printing press.", "Introduced the concept of the tragic hero to Western literature.", "Was written entirely in Latin for the religious elite."],

  // --- Unit 5: Modernism & Contemporary Literature ---
  [5, "The 'Stream of Consciousness' narrative technique is designed to:", "Replicate the unfiltered, continuous flow of a character's inner thoughts.", "Provide a highly structured, objective timeline of historical events.", "Ensure the narrator speaks directly to the reader in the second person.", "Summarize the plot explicitly at the beginning of every chapter."],
  [5, "F. Scott Fitzgerald's 'The Great Gatsby' heavily critiques which aspect of American society?", "The moral decay and shallow materialism of the Roaring Twenties.", "The brutal reality of trench warfare during World War I.", "The harsh, unsanitary conditions of the meatpacking industry.", "The strict, oppressive religious culture of early Puritans."],
  [5, "Which defining characteristic of 'Modernist' literature was a direct response to the devastation of World War I?", "A sense of profound disillusionment, fragmentation, and loss of meaning.", "A return to highly structured, rhyming romantic poetry.", "An unwavering belief in the inevitable progress of human technology.", "A focus on creating idealized, flawless heroic protagonists."],
  [5, "The Harlem Renaissance was a literary movement centered on:", "The celebration of African American culture, heritage, and artistic expression.", "The experiences of poor, white sharecroppers in the Deep South.", "The disillusionment of American expatriates living in Paris.", "The exploration of magical realism by Latin American authors."],
  [5, "In Arthur Miller's 'The Crucible', the Salem witch trials serve as an allegory for:", "The anti-Communist hysteria of the McCarthy era.", "The devastation caused by the Spanish Flu epidemic.", "The rising tensions between the US and the Soviet Union during the Cuban Missile Crisis.", "The systemic corruption of the American judicial system in the 1990s."],
  [5, "A narrative technique in which the author uses humor, irony, or exaggeration to expose and criticize societal flaws is known as:", "Satire", "Melodrama", "Tragedy", "Eulogy"],

  // --- Miscellaneous Grammar & Rhetoric (Units 6-9) ---
  [6, "What is a 'syllogism' in rhetorical argument?", "A form of deductive reasoning consisting of a major premise, a minor premise, and a conclusion.", "A deliberate exaggeration used to shock the audience into action.", "A circular argument where the conclusion is hidden in the premise.", "An emotional appeal that completely bypasses logical evidence."],
  [6, "The phrase 'ask not what your country can do for you, ask what you can do for your country' is an example of:", "Chiasmus", "Litotes", "Simile", "Onomatopoeia"],
  [7, "Which of the following sentences contains a 'dangling modifier'?", "Walking down the street, the trees were beautiful.", "The student hurriedly finished her essay before the bell rang.", "Despite the heavy rain, the football game continued as planned.", "The old dog slept soundly on the living room rug."],
  [8, "In literary analysis, what is the difference between 'tone' and 'mood'?", "Tone is the author's attitude toward the subject; mood is the feeling created in the reader.", "Tone relies on imagery; mood relies on strict metrical structures.", "Tone is always objective and factual; mood is always subjective and biased.", "Tone is determined by the publisher; mood is determined by the genre."],
  [9, "When an author provides hints or clues about events that will happen later in the narrative, they are utilizing:", "Foreshadowing", "Flashback", "Deus Ex Machina", "In Medias Res"]
];
