// ==========================================
// MASTER QUESTION BANK (APUSH & AP Gov)
// Format: [Unit/Period, "Question Text", "Correct Answer", "Wrong 1", "Wrong 2", "Wrong 3"]
// ==========================================

const apushBank = [
  // --- PERIOD 1 (1491-1607) ---
  [1,"How did the cultivation of maize primarily impact pre-Columbian Native American societies?","It supported economic development, settlement, and social diversification.","It led to rapid desertification of the Great Plains.","It forced indigenous populations to adopt nomadic lifestyles.","It prevented the establishment of large trade networks."],
  [1,"What was the primary goal of the Spanish encomienda system?","To extract labor from Native Americans while ostensibly converting them to Christianity.","To establish equal trade alliances with the Aztec Empire.","To grant sovereign land rights to indigenous leaders.","To completely replace Native laborers with indentured Europeans."],
  [1,"How did Native Americans in the Great Basin and western Plains primarily adapt to their environment?","By developing highly mobile, nomadic lifestyles focused on hunting.","By constructing massive irrigation networks for intensive farming.","By establishing permanent, multi-story cliff dwellings.","By relying exclusively on fishing and whaling economies."],
  [1,"Which factor was most responsible for the drastic decline of Native American populations after 1492?","The introduction of Eurasian diseases like smallpox to which they had no immunity.","Protracted military conflicts with English settlers.","Widespread famine caused by European agricultural practices.","The mass migration of indigenous peoples to South America."],
  [1,"What was the central argument of Bartolomé de las Casas regarding Spanish colonization?","He strongly condemned the brutal treatment of Native Americans.","He argued that the encomienda system was divinely ordained.","He advocated for the immediate enslavement of all indigenous peoples.","He believed Native Americans should be forced off their ancestral lands."],
  
  // --- PERIOD 2 (1607-1754) ---
  [2,"What was the primary economic motivation for the founding of Jamestown?","To generate profits for the investors of the Virginia Company.","To establish a religious haven for persecuted Puritans.","To create an egalitarian society based on subsistence farming.","To build a strategic military base against the French."],
  [2,"How did the development of tobacco cultivation affect the Chesapeake colonies?","It created a heavy reliance on indentured servitude and later African slavery.","It led to the rapid development of large, bustling urban centers.","It promoted peaceful and cooperative relations with the Powhatan.","It encouraged the establishment of public schools and universities."],
  [2,"Which of the following was a key characteristic of the New England colonies?","They were settled by families seeking religious freedom and built tight-knit communities.","They relied primarily on the cultivation of cash crops like rice and indigo.","They featured a highly unequal society dominated by a small planter elite.","They actively encouraged the immigration of diverse religious groups like Catholics."],
  [2,"What was the primary cause of Bacon's Rebellion in 1676?","Frustration of poor backcountry farmers over the governor's Native American policies.","A dispute over the enforcement of the British Navigation Acts.","Religious tension between Anglicans and dissenting Puritans.","A slave uprising aimed at ending the plantation system in Virginia."],
  [2,"The Middle Colonies (New York, Pennsylvania) were distinct because they:","Featured demographic, religious, and ethnic diversity with a thriving export economy.","Relied almost entirely on enslaved African labor for tobacco farming.","Maintained strict religious conformity governed by Puritan theology.","Were entirely neglected by the British government until the 1750s."],

  // --- PERIOD 3 (1754-1800) ---
  [3,"What was the primary consequence of the French and Indian War for Great Britain?","It left Britain with massive debt, leading to new taxes on the colonies.","It resulted in the immediate loss of all British territory in North America.","It ushered in an era of unprecedented political autonomy for the colonies.","It caused the British Parliament to abolish the mercantilist system."],
  [3,"The Proclamation of 1763 angered American colonists because it:","Banned colonial settlement west of the Appalachian Mountains.","Imposed a direct tax on all printed materials in the colonies.","Required colonists to provide housing and food for British troops.","Granted a monopoly on the tea trade to the East India Company."],
  [3,"What was the main argument of the colonists against the Stamp Act?","Only their elected colonial assemblies had the right to tax them directly.","The tax rate was too high for the average farmer to afford.","The revenue was being used to fund wars in Europe rather than America.","It violated their right to freely trade with the French West Indies."],
  [3,"Thomas Paine’s 'Common Sense' was highly influential because it:","Used clear, persuasive language to argue for independence and a republic.","Detailed a comprehensive military strategy for defeating the British army.","Proposed a specific framework for the United States Constitution.","Argued that the colonies should seek reconciliation with King George III."],
  [3,"Which Enlightenment thinker's ideas about natural rights heavily influenced the Declaration of Independence?","John Locke","Thomas Hobbes","Jean-Jacques Rousseau","Voltaire"],

  // --- PERIOD 4 (1800-1848) ---
  [4,"What was the significance of the Supreme Court ruling in Marbury v. Madison (1803)?","It established the principle of judicial review over federal laws.","It upheld the constitutionality of the National Bank.","It declared that states could not tax federal institutions.","It ruled that Native American tribes were sovereign nations."],
  [4,"Why was Thomas Jefferson initially hesitant to authorize the Louisiana Purchase?","The Constitution did not explicitly grant the president power to purchase land.","He feared it would upset relations with the British Empire.","He believed the land was too vast and uninhabitable for farming.","He thought it would accelerate the industrialization of the United States."],
  [4,"The Market Revolution of the early 19th century was characterized by:","The shift toward commercial agriculture and specialized industrial production.","A decline in urbanization as people moved to frontier farms.","The complete eradication of the institution of slavery.","A return to self-sufficient, localized barter economies."],
  [4,"Which of the following was a major effect of the construction of the Erie Canal?","It dramatically lowered the cost of shipping goods between the Midwest and the East Coast.","It caused the economic decline of New York City in favor of New Orleans.","It completely eliminated the need for railroad construction in the North.","It directly led to the outbreak of the War of 1812."],
  [4,"The primary objective of the Monroe Doctrine was to:","Prevent European powers from establishing new colonies in the Western Hemisphere.","Assert the right of the United States to expand into Canada and Mexico.","Form a permanent military alliance with Great Britain against France.","Justify the forced removal of Native Americans from the Southeast."],

  // --- PERIOD 5 (1844-1877) ---
  [5,"The ideology of Manifest Destiny was used to justify:","The westward expansion of the US to the Pacific Ocean.","The strict containment of slavery to the South.","The immediate assimilation of Native Americans.","The establishment of an overseas American empire."],
  [5,"Which event directly sparked the Mexican-American War?","A dispute over the southern boundary of Texas.","The Mexican attack on the Alamo.","The publication of the Ostend Manifesto.","The US annexation of California."],
  [5,"The Wilmot Proviso controversially proposed that:","Slavery be banned in any territory acquired from Mexico.","California be admitted as a slave state.","The Missouri Compromise line be extended to the Pacific.","Popular sovereignty decide the fate of all new territories."],
  [5,"A major component of the Compromise of 1850 that outraged Northerners was the:","Passage of a much stricter Fugitive Slave Act.","Abolition of the slave trade in Washington D.C.","Admission of California as a free state.","Implementation of popular sovereignty in Utah and New Mexico."],
  [5,"Uncle Tom's Cabin heavily influenced public opinion by:","Personalizing the brutal reality of slavery for Northern readers.","Providing a historical defense of the plantation system.","Arguing for the immediate colonization of freedmen in Africa.","Exposing the political corruption of the Buchanan administration."],

  // --- PERIOD 6 (1865-1898) ---
  [6,"The completion of the Transcontinental Railroad in 1869 had which major economic impact?","It integrated national markets and spurred rapid industrial and western development.","It immediately collapsed the agricultural economy of the Midwest.","It ended the era of massive European immigration to the East Coast.","It caused a drastic decline in the profitability of the steel industry."],
  [6,"What was the primary purpose of the Homestead Act of 1862?","To encourage western settlement by offering 160 acres of free land to farmers.","To provide land grants for the construction of transcontinental railroads.","To establish reservations for Native American tribes displaced by white settlers.","To allocate federal lands for the creation of agricultural colleges."],
  [6,"The Dawes Severalty Act of 1887 was an attempt to assimilate Native Americans by:","Breaking up tribal reservations into individual farming plots.","Sending Native American children to federally funded boarding schools.","Granting full US citizenship to all Native Americans.","Encouraging the preservation of traditional indigenous religions like the Ghost Dance."],
  [6,"Andrew Carnegie's concept of the 'Gospel of Wealth' argued that:","The wealthy had a moral obligation to use their fortunes for the public good.","Unfettered capitalism was a sin against Christian teachings.","The government should heavily tax the rich to distribute wealth evenly.","Labor unions were essential to maintaining a fair and moral economy."],
  [6,"During the Gilded Age, the theory of Social Darwinism was frequently used to:","Justify extreme wealth inequality and unregulated laissez-faire capitalism.","Argue for extensive government regulation of monopolies.","Promote social welfare programs for the urban poor.","Support the rights of workers to collectively bargain."],

  // --- PERIOD 7 (1890-1945) ---
  [7,"Muckrakers like Upton Sinclair and Ida Tarbell were journalists who:","Exposed political corruption and corporate abuses to spark public reform.","Wrote sensationalist yellow journalism to start the Spanish-American War.","Promoted the extreme laissez-faire economic policies of the Gilded Age.","Defended the actions of political machines like Tammany Hall."],
  [7,"Which of the following was a primary motivation for American imperialism in the 1890s?","The desire for new overseas markets and naval coaling stations.","A need to acquire new land for mass European immigration.","The goal of spreading democratic institutions to the nations of Europe.","A commitment to upholding the Monroe Doctrine globally."],
  [7,"The Spanish-American War resulted in the United States acquiring which territories?","The Philippines, Puerto Rico, and Guam.","Cuba, Hawaii, and Alaska.","The Dominican Republic, Haiti, and the Virgin Islands.","Panama, Nicaragua, and Mexico."],
  [7,"The Roosevelt Corollary to the Monroe Doctrine stated that the US had the right to:","Intervene militarily in Latin American nations to maintain order and collect debts.","Annex any territory in the Western Hemisphere by force.","Prevent any Asian immigration into the United States.","Establish free trade agreements across all of South America."],
  [7,"Which event was the immediate catalyst for the United States entering World War I?","The interception of the Zimmermann Telegram and unrestricted submarine warfare.","The assassination of Archduke Franz Ferdinand.","The sinking of the RMS Lusitania in 1915.","The Russian Bolshevik Revolution."],

  // --- PERIOD 8 (1945-1980) ---
  [8,"The Truman Doctrine established the US foreign policy of:","Containment, committing to support free peoples resisting communist subjugation.","Massive retaliation, threatening nuclear war against any Soviet aggression.","Détente, seeking peaceful coexistence and arms reduction with the USSR.","Isolationism, withdrawing all American troops from Europe."],
  [8,"The Marshall Plan aimed to prevent the spread of communism by:","Providing massive economic aid to rebuild the devastated economies of Western Europe.","Forming a mutual defense pact with democratic nations (NATO).","Engaging in a massive buildup of conventional military forces.","Dropping supplies into blockaded cities, as seen in Berlin."],
  [8,"The Second Red Scare and McCarthyism were characterized by:","Aggressive, often unsubstantiated accusations of communist infiltration in the US government.","A highly successful effort to uncover hundreds of actual Soviet spies.","The complete outlawing of the Democratic Party.","A focus entirely on exposing communists in the Hollywood film industry."],
  [8,"The Supreme Court's landmark decision in Brown v. Board of Education (1954) ruled that:","Racial segregation in public schools was inherently unequal and unconstitutional.","The 'separate but equal' doctrine applied only to elementary schools.","Busing was an illegal method for achieving school integration.","The federal government could not interfere with state education policies."],
  [8,"Martin Luther King Jr.'s strategy for achieving civil rights relied primarily on:","Nonviolent civil disobedience and peaceful mass protests.","Armed self-defense and black nationalism.","Lengthy legal battles in federal courts exclusively.","The gradual accommodation of Jim Crow laws."],

  // --- PERIOD 9 (1980-Present) ---
  [9,"The 'Reagan Revolution' of the 1980s was characterized by a conservative agenda that emphasized:","Tax cuts, deregulation of business, and a massive increase in military spending.","The rapid expansion of federal welfare programs.","A policy of strict détente and arms reduction with the Soviet Union.","The nationalization of major industries and banks."],
  [9,"What was a major consequence of the Persian Gulf War (1991)?","A successful US-led coalition expelled Iraqi forces from Kuwait.","Saddam Hussein was immediately removed from power and executed.","The US permanently annexed the oil fields of the Middle East.","The United Nations was dissolved due to its failure to act."],
  [9,"The North American Free Trade Agreement (NAFTA), signed in 1993, aimed to:","Eliminate trade barriers between the US, Canada, and Mexico.","Create a single currency for the Western Hemisphere.","Prevent the outsourcing of American manufacturing jobs.","Establish a mutual defense pact against European aggression."],
  [9,"How did US foreign policy drastically shift following the September 11, 2001 terrorist attacks?","The US launched a global 'War on Terror,' leading to invasions of Afghanistan and Iraq.","The US retreated into strict isolationism to protect the homeland.","The US formed a permanent military alliance with the Russian Federation.","The US immediately withdrew all military forces from the Middle East."],
  [9,"The Great Recession of 2008 was triggered primarily by the collapse of the:","Housing market due to risky subprime mortgage lending.","Tech industry following the burst of the dot-com bubble.","Global oil supply due to conflicts in the Middle East.","American automotive industry's manufacturing base."]
];

// ==========================================
// AP GOV FOUNDATIONAL DOCUMENTS BANK
// 9 Documents 
// ==========================================

const apGovBank = [
  // --- DOC 1: Declaration of Independence ---
  [1, "In the Declaration of Independence, the phrase 'Laws of Nature and of Nature's God' reflects which philosophical concept?", "Natural Rights", "Divine Right of Kings", "Socialism", "Checks and Balances"],
  [1, "According to the Declaration, all men are endowed by their Creator with certain unalienable rights, including:", "Life, Liberty, and the pursuit of Happiness", "Property, Wealth, and Security", "Voting, Speech, and Religion", "Life, Liberty, and Property"],
  [1, "The Declaration asserts that government power comes directly from the:", "Consent of the governed", "Military superiority of the state", "Divine appointment by God", "Wealth of the ruling class"],
  [1, "If a government becomes destructive and consistently abuses its power, the Declaration states the people have the right to:", "Alter or abolish it", "Submit to its authority patiently", "Petition the king repeatedly", "Relocate to another country"],
  [1, "Which of the following was listed as a 'Military' grievance in the Declaration?", "Maintaining standing armies in times of peace without consent", "Imposing taxes without representation", "Dissolving representative legislatures", "Cutting off trade with all parts of the world"],
  [1, "The Declaration states that a long train of abuses signals a move toward:", "Absolute Despotism (Tyranny)", "A pure democracy", "An egalitarian society", "Economic prosperity"],
  [1, "In the Declaration of Sovereignty, the colonies declared they were absolved from all allegiance to the:", "British Crown", "French Monarchy", "Native American tribes", "Articles of Confederation"],
  [1, "To justify their separation, the authors argue they must declare the causes to:", "The opinions of mankind", "Only the British Parliament", "Only the colonial legislatures", "The Supreme Court"],
  [1, "Which philosopher heavily influenced Jefferson's writing of the Declaration of Independence?", "John Locke", "Thomas Hobbes", "Niccolò Machiavelli", "Karl Marx"],
  [1, "In the conclusion, what do the signers mutually pledge to each other?", "Their Lives, their Fortunes, and their sacred Honor", "Their land, their money, and their weapons", "Their loyalty to a new king", "Their submission to the Articles of Confederation"],
  [1, "The Declaration is fundamentally an argument for:", "The right to self-government and revolution", "The necessity of a strong central executive", "The establishment of a national bank", "The expansion of British territory"],
  [1, "Which of these is an 'Economic' grievance mentioned in the document?", "Imposing taxes on us without our consent", "Quartering large bodies of armed troops", "Depriving us of the benefits of trial by jury", "Suspending our own legislatures"],
  [1, "Before declaring independence, the colonists claimed they repeatedly warned the British of their:", "Unwarrantable jurisdiction over us", "Desire to conquer France", "Inability to pay any taxes", "Intent to establish a monarchy"],
  [1, "Which core principle of government is established when Jefferson writes that governments are instituted 'to secure these rights'?", "Limited Government", "Federalism", "Judicial Review", "Checks and Balances"],
  [1, "The Declaration explicitly claims the new states have the power to do all of the following EXCEPT:", "Establish a permanent national religion", "Levy War and conclude Peace", "Contract Alliances", "Establish Commerce"],

  // --- DOC 2: Articles of Confederation ---
  [2, "Under the Articles of Confederation, the national government was best described as a:", "Firm league of friendship", "Strong, centralized republic", "Unitary state", "Constitutional monarchy"],
  [2, "Which level of government retained its 'sovereignty, freedom, and independence' under the Articles?", "The States", "The National Congress", "The Executive Branch", "The Federal Judiciary"],
  [2, "What was a major weakness of Congress under the Articles of Confederation?", "It lacked the power to tax the people directly.", "It could not declare war or make peace.", "It was dominated by a powerful President.", "It allowed large states to have more votes than small states."],
  [2, "How many votes did each state receive in the Confederation Congress, regardless of population?", "One vote", "Two votes", "Proportional to population", "Three votes"],
  [2, "To pass any major law under the Articles, how many states had to agree?", "9 out of 13", "A simple majority (7 out of 13)", "All 13 states", "Only the 4 largest states"],
  [2, "To alter or amend the Articles of Confederation, what was required?", "Unanimous consent from all 13 state legislatures.", "A two-thirds vote in Congress.", "Approval by the President.", "A national popular referendum."],
  [2, "Under the Articles, who held the power to regulate interstate commerce?", "The individual states", "The national Congress", "The federal courts", "The President"],
  [2, "Which of the following branches did NOT exist under the Articles of Confederation?", "An Executive Branch and a Federal Judiciary", "A Legislative Branch", "State governments", "A postal service"],
  [2, "The Articles of Confederation were intentionally designed to be weak in order to:", "Prevent the kind of tyranny experienced under British rule.", "Ensure the quick collapse of the national government.", "Force the states into a civil war.", "Allow France to take over the western territories."],
  [2, "Shays' Rebellion demonstrated that the Articles of Confederation:", "Could not effectively maintain order or put down domestic uprisings.", "Were highly efficient at collecting federal taxes.", "Created an executive that was too powerful.", "Perfectly protected the property rights of farmers."],
  [2, "Under the Articles, the national government could raise an army only by:", "Requesting troop quotas from the states.", "Drafting citizens directly.", "Hiring foreign mercenaries exclusively.", "Forcing state governors to serve as generals."],
  [2, "The phrase 'perpetual Union' in the document indicated that:", "The states intended to remain unified permanently.", "The government would expire after 20 years.", "The President would serve for life.", "All states had to share the exact same laws."],
  [2, "Why was the lack of a federal judiciary a problem under the Articles?", "There was no national court to settle disputes between states.", "Congress spent too much time hearing murder trials.", "States could not write their own local laws.", "The Supreme Court kept striking down state laws."],
  [2, "Under the Articles, which entity had the exclusive power to coin money?", "Both the states and the national government could coin money, leading to inflation.", "Only the national government.", "Only the state of New York.", "No one was allowed to use paper money."],
  [2, "The success of the Articles of Confederation is often attributed solely to its handling of:", "The western land claims (Northwest Ordinance).", "The establishment of a national bank.", "The complete elimination of the national debt.", "The quick suppression of domestic rebellions."],

  // --- DOC 3: Brutus 1 ---
  [3, "Brutus 1 represents the perspective of which political group?", "The Anti-Federalists", "The Federalists", "The Whigs", "The Loyalists"],
  [3, "What is Brutus's primary concern regarding the proposed Constitution?", "It will create a large, consolidated republic that will destroy state sovereignty.", "It does not give the national government enough power to tax.", "It creates an executive branch that is too weak.", "It fails to establish a standing army."],
  [3, "Brutus argues that a free republic cannot exist over a large territory because:", "The representatives will be too far removed from the people to understand their needs.", "A large territory cannot physically be defended from invasion.", "Large territories lack the natural resources to sustain a government.", "People in large territories refuse to pay taxes."],
  [3, "Which constitutional clause does Brutus fear will give the federal government absolute and uncontrollable power?", "The Necessary and Proper Clause and the Supremacy Clause", "The Commerce Clause", "The Equal Protection Clause", "The Three-Fifths Clause"],
  [3, "Brutus warns that the federal power to tax will ultimately lead to:", "The complete dissolution and starvation of the state governments.", "Massive economic prosperity for all citizens.", "A perfectly balanced budget.", "The immediate abolition of slavery."],
  [3, "According to Brutus, what will happen to state courts under the proposed Constitution?", "They will be overshadowed and rendered obsolete by the federal courts.", "They will be given ultimate authority over federal law.", "They will completely absorb the federal judiciary.", "They will only hear cases involving foreign diplomats."],
  [3, "Brutus believed that in a republic, the manners, sentiments, and interests of the people should be:", "Similar, otherwise there will be constant clashing and gridlock.", "As diverse as possible to encourage debate.", "Dictated entirely by the wealthy elite.", "Enforced strictly by a standing army."],
  [3, "How does Brutus view the creation of a standing army in peacetime?", "As a dangerous tool that rulers use to enforce their will and destroy liberty.", "As an essential necessity for protecting a large republic.", "As the only way to ensure states pay their taxes.", "As a harmless institution that provides jobs."],
  [3, "Brutus cites which Enlightenment philosopher to support his argument that republics must be small?", "Montesquieu", "John Locke", "Thomas Hobbes", "Jean-Jacques Rousseau"],
  [3, "According to Brutus, what will happen to the representatives in a large republic?", "They will abuse their power for self-interest and become above the control of the people.", "They will act purely out of civic virtue.", "They will constantly consult their constituents before making decisions.", "They will inevitably vote to dissolve the national government."],
  [3, "Brutus argues that the federal government's power to raise an army will lead to:", "The destruction of liberty.", "The expansion of the United States into Canada.", "The immediate defeat of European powers.", "A permanent era of peace."],
  [3, "The main rhetorical goal of Brutus 1 was to convince the people of New York to:", "Reject the ratification of the proposed Constitution.", "Immediately elect George Washington as King.", "Demand the removal of the Bill of Rights.", "Invade neighboring states."],
  [3, "Brutus fears that the Supremacy Clause will:", "Make state laws and constitutions entirely void if they conflict with federal goals.", "Allow states to easily nullify federal laws.", "Give the Supreme Court the power to impeach the President.", "Force the federal government to obey state courts."],
  [3, "Why does Brutus believe a large republic will result in tyranny?", "Because a diverse population will constantly argue, requiring a strong, oppressive force to maintain order.", "Because the wealthy will refuse to participate in government.", "Because the states will peacefully agree to give up all their power.", "Because a large republic cannot afford to build prisons."],
  [3, "Ultimately, Brutus 1 serves as a foundational text arguing for:", "States' rights and decentralized power.", "A strong, energetic executive.", "An independent federal judiciary.", "The necessity of factions in a democracy."],

  // --- DOC 4: Federalist 10 ---
  [4, "Who is the author of Federalist 10?", "James Madison", "Alexander Hamilton", "John Jay", "Thomas Jefferson"],
  [4, "In Federalist 10, what does Madison identify as the primary danger to a popular government?", "The violence of faction.", "The weakness of the executive branch.", "The existence of state governments.", "The lack of a standing army."],
  [4, "How does Madison define a 'faction'?", "A group of citizens united by a common passion or interest, adverse to the rights of others or the community.", "A perfectly balanced, bipartisan political party.", "A small group of elite, wealthy landowners.", "A peaceful protest organized by citizens."],
  [4, "Madison argues there are two methods of curing the mischiefs of faction: removing its causes and:", "Controlling its effects.", "Executing its leaders.", "Banning all political speech.", "Eliminating property rights."],
  [4, "Why does Madison argue that removing the causes of faction is impossible?", "It would require destroying liberty or making every citizen hold the exact same opinions.", "It would cost too much money to enforce.", "The Constitution explicitly protects the right to riot.", "Foreign nations would immediately invade."],
  [4, "According to Madison, what is the most common and durable source of factions?", "The various and unequal distribution of property.", "Religious differences.", "Geographic locations.", "Loyalty to different political leaders."],
  [4, "How does a 'republic' differ from a 'pure democracy' according to Madison?", "A republic delegates government to a small number of elected citizens over a larger sphere.", "A republic allows every citizen to vote directly on every law.", "A republic is ruled by a single, unchecked monarch.", "A republic requires unanimous consent to pass laws."],
  [4, "Madison argues that a large republic is better than a small one at controlling factions because:", "It includes a greater variety of parties and interests, making it harder for one majority faction to dominate.", "It allows the military to crush rebellions more quickly.", "It guarantees that all politicians will be perfectly virtuous.", "It prevents poor people from voting."],
  [4, "The argument in Federalist 10 completely contradicts the anti-federalist argument found in:", "Brutus 1", "The Declaration of Independence", "Federalist 51", "Federalist 78"],
  [4, "Madison asserts that factious leaders might kindle a flame within their own state, but:", "They will be unable to spread a general conflagration through the other states.", "They will immediately take over the federal government.", "They will easily rewrite the Constitution.", "They will always be elected to the Presidency."],
  [4, "Federalist 10 supports the concept of 'Pluralism', which suggests that:", "Multiple competing interests naturally balance each other out in a large republic.", "Only a single, unified political party should exist.", "The wealthy elite should control all aspects of government.", "States should be completely independent and sovereign."],
  [4, "Madison believed that elected representatives in a large republic would:", "Filter and refine the public views to best serve the true interest of the country.", "Blindly follow whatever the angry mob demanded.", "Instantly become corrupt tyrants.", "Ignore the Constitution entirely."],
  [4, "In Federalist 10, the phrase 'Liberty is to faction what air is to fire' implies that:", "Factions are a natural, unavoidable byproduct of freedom.", "Liberty must be extinguished to achieve peace.", "Factions provide the oxygen needed to build a strong economy.", "Freedom of speech directly causes physical fires."],
  [4, "Which of the following would Madison consider a dangerous 'faction'?", "A majority group seeking to seize property from the wealthy minority.", "A lone citizen writing a letter to their congressman.", "The Supreme Court striking down a law.", "The President vetoing a bill."],
  [4, "Ultimately, Federalist 10 argues that the structure of the proposed Constitution provides a 'republican remedy' to:", "The diseases most incident to republican government (like tyranny of the majority).", "The military threats posed by Great Britain.", "The economic depression caused by the Revolutionary War.", "The lack of religious freedom in the colonies."],

  // --- DOC 5: Federalist 70 ---
  [5, "Who wrote Federalist 70?", "Alexander Hamilton", "James Madison", "John Jay", "George Washington"],
  [5, "What is the central thesis of Federalist 70?", "A strong, energetic executive is essential for a good and successful government.", "The executive branch must be divided among three people to prevent tyranny.", "The President should have no power over the military.", "The legislative branch should have total control over the executive."],
  [5, "Hamilton argues that 'Energy in the Executive' is necessary for all of the following EXCEPT:", "Creating laws and levying taxes.", "Protection against foreign attacks.", "The steady administration of the laws.", "Security of liberty against the assaults of ambition and anarchy."],
  [5, "According to Hamilton, a feeble executive implies:", "A feeble execution of the government, leading to bad government.", "A perfectly balanced, peaceful republic.", "A government that strictly follows the Constitution.", "A state where the courts have all the power."],
  [5, "Hamilton strongly opposes the idea of a 'plural executive' (a council of presidents) because it would lead to:", "Disagreements, concealed faults, and a lack of accountability.", "Too much efficiency and rapid lawmaking.", "A military dictatorship.", "Immediate bankruptcy for the nation."],
  [5, "Why does a single executive ensure greater accountability?", "Because the public and the press know exactly who to blame for failures.", "Because a single person is physically incapable of committing crimes.", "Because the Supreme Court watches them constantly.", "Because they are forced to resign if they make a mistake."],
  [5, "In a plural executive, when things go wrong, Hamilton argues the members will:", "Blame each other, making it impossible to determine who is truly at fault.", "Immediately confess and resign together.", "Unite to overthrow the legislature.", "Pay for the damages out of their own pockets."],
  [5, "Hamilton argues that a single executive allows for more 'secrecy and dispatch', which is especially vital in:", "Conducting foreign policy and military operations.", "Debating local tax rates.", "Writing the federal budget.", "Appointing low-level post office workers."],
  [5, "Which historical example does Hamilton use to warn against divided power?", "The Roman Republic's use of a Dictator during emergencies.", "The French Revolution.", "The signing of the Magna Carta.", "The Spanish Inquisition."],
  [5, "Hamilton claims that a plural executive deprives the people of their two greatest securities: the restraints of public opinion and:", "The ability to discover with facility whom to punish or remove from office.", "The right to bear arms against the government.", "The freedom of the press.", "The power to print paper money."],
  [5, "Opponents of the Constitution feared a single executive would become a monarch. How did Hamilton respond?", "He argued a single executive is actually easier to watch and hold accountable than a secretive council.", "He agreed and said America needed a king.", "He stated the President would have no real power anyway.", "He argued the states would easily defeat the President in a war."],
  [5, "Which ingredient of executive energy requires the President to not have to consult a council before acting in a crisis?", "Dispatch (speed)", "Duration", "Adequate provision (salary)", "Competent powers"],
  [5, "Federalist 70 directly defends which Article of the Constitution?", "Article II (The Executive Branch)", "Article I (The Legislative Branch)", "Article III (The Judicial Branch)", "Article V (The Amendment Process)"],
  [5, "What does Hamilton argue happens when two or more people are engaged in any common enterprise?", "There is always the danger of difference of opinion and personal emulation.", "They perfectly combine their strengths to succeed.", "They naturally defer to the smartest person.", "They eliminate the need for a legislative branch."],
  [5, "The phrase 'a clog upon his good intentions' is used by Hamilton to describe:", "An executive council that hinders a single leader's ability to act quickly.", "The Supreme Court striking down executive orders.", "Congress refusing to pass the President's budget.", "The media criticizing the President."],

  // --- DOC 6: Federalist 51 ---
  [6, "Who wrote Federalist 51?", "James Madison", "Alexander Hamilton", "Thomas Jefferson", "Patrick Henry"],
  [6, "What is the primary topic of Federalist 51?", "Separation of powers and checks and balances.", "The necessity of a Bill of Rights.", "The creation of a national bank.", "The evils of the transatlantic slave trade."],
  [6, "Complete Madison's famous quote: 'Ambition must be made to counteract...'?", "Ambition", "Tyranny", "Liberty", "Faction"],
  [6, "Madison argues that government is necessary because:", "Men are not angels.", "Property must be redistributed equally.", "Foreign nations are inherently hostile.", "The states requested it."],
  [6, "According to Madison, what is the great difficulty in framing a government?", "You must first enable the government to control the governed, and then oblige it to control itself.", "You must ensure everyone has equal wealth.", "You must prevent the creation of a military.", "You must outlaw political parties."],
  [6, "To prevent any one branch from becoming too powerful, Madison suggests:", "Giving each branch constitutional means and personal motives to resist encroachments by the others.", "Making the President serve for life.", "Allowing the military to oversee the courts.", "Making all politicians serve without pay."],
  [6, "In a republican government, which branch does Madison claim naturally predominates?", "The Legislative branch.", "The Executive branch.", "The Judicial branch.", "The Military."],
  [6, "To prevent the legislative branch from becoming tyrannical, Madison proposes:", "Dividing the legislature into two different houses with different modes of election.", "Giving the President an absolute, un-overrideable veto.", "Allowing the Supreme Court to write laws.", "Holding elections every single month."],
  [6, "Federalist 51 describes the US system as a 'compound republic', meaning power is first divided:", "Between the state and federal governments (Federalism), and then subdivided among separate departments.", "Between the rich and the poor.", "Between the North and the South.", "Between the Senate and the House of Representatives."],
  [6, "Madison argues that a multiplicity of interests and sects in society will:", "Prevent any one majority group from unfairly oppressing a minority.", "Inevitably lead to a violent civil war.", "Make it impossible to pass any laws.", "Require the government to establish a national religion."],
  [6, "According to Federalist 51, the 'interior structure of the government' must be contrived so that its parts:", "Keep each other in their proper places.", "Function entirely independently without any interaction.", "Always agree on every policy.", "Are completely controlled by the President."],
  [6, "How should the members of each branch be chosen, ideally, according to Madison?", "They should be drawn from the same fountain of authority, the people, but through different channels.", "They should all be appointed directly by the President.", "They should be selected by the state governors.", "They should inherit their positions."],
  [6, "Madison acknowledges that the Judiciary is an exception to the strict rule of democratic election because:", "Judges require peculiar qualifications and need life tenure to remain independent.", "Judges are too unpopular to win elections.", "The Constitution forbids lawyers from voting.", "The courts have no real power anyway."],
  [6, "The phrase 'If angels were to govern men, neither external nor internal controls on government would be necessary' justifies:", "The system of checks and balances.", "The need for a pure democracy.", "The creation of a dictatorship.", "The abolition of taxes."],
  [6, "Ultimately, Federalist 51 argues that the Constitution protects liberty by:", "Pitting power against power to prevent the concentration of authority in one place.", "Relying entirely on the good morals and virtue of elected politicians.", "Eliminating the national government entirely.", "Giving all power to the state legislatures."],

  // --- DOC 7: Federalist 78 ---
  [7, "Who authored Federalist 78?", "Alexander Hamilton", "James Madison", "Thomas Jefferson", "George Mason"],
  [7, "What branch of government is the focus of Federalist 78?", "The Judicial Branch", "The Executive Branch", "The Legislative Branch", "The Bureaucracy"],
  [7, "Hamilton famously describes the judiciary as the branch that is:", "The least dangerous to the political rights of the Constitution.", "The most tyrannical of the three branches.", "The absolute ruler of the states.", "The primary creator of federal laws."],
  [7, "According to Hamilton, the judiciary has 'no influence over either the sword or the purse', meaning it has neither:", "Force nor will, but merely judgment.", "Money nor popularity, but only fear.", "Armies nor navies, but only taxes.", "Elections nor appointments, but only vetoes."],
  [7, "Why does Hamilton argue that federal judges must have life tenure (serving during 'good behavior')?", "To ensure their absolute independence from the other branches and the political passions of the public.", "To ensure they become wealthy.", "Because it takes too long to train new judges.", "Because no one else wants the job."],
  [7, "Federalist 78 lays the philosophical groundwork for which vital judicial power?", "Judicial Review", "Executive Privilege", "The Filibuster", "Impeachment"],
  [7, "Hamilton argues that if a legislative act conflicts with the Constitution, the courts must:", "Declare the legislative act void, as the Constitution is the fundamental law.", "Enforce the legislative act, since the legislature is elected.", "Ask the President what to do.", "Rewrite the Constitution to match the law."],
  [7, "According to Federalist 78, the courts were designed to be an intermediate body between:", "The people and the legislature, to keep the latter within the limits of their authority.", "The states and the foreign powers.", "The military and the civilians.", "The President and the Cabinet."],
  [7, "Hamilton argues that the Constitution is the declared will of the people, therefore:", "It is superior to the will of the legislature (statutory law).", "It can be easily changed by a simple majority in Congress.", "It only applies to the federal government, not the states.", "It must be renewed every 20 years."],
  [7, "Without an independent judiciary, Hamilton warns that:", "All the reservations of particular rights or privileges would amount to nothing.", "The President would immediately become a king.", "The states would declare war on each other.", "The military would refuse to fight."],
  [7, "How does Hamilton respond to the fear that the courts will become too powerful?", "He states they are inherently weak because they depend entirely on the executive to enforce their rulings.", "He agrees and suggests limiting them to only hearing 10 cases a year.", "He suggests the military should oversee the courts.", "He argues the legislature can fire judges at any time for bad decisions."],
  [7, "The requirement that judges serve during 'good behavior' is cited by Hamilton as an excellent barrier to the encroachments of:", "The representative body (Congress).", "Foreign spies.", "State governors.", "The Electoral College."],
  [7, "Hamilton asserts that it takes a long time to fully understand the complexities of the law, which further justifies:", "Permanent (life) tenure for judges so they have time to master the precedents.", "Paying judges an extremely low salary.", "Forcing judges to retire at age 50.", "Allowing any citizen to be a judge without training."],
  [7, "In Federalist 78, 'judgment' is the only power the courts possess, whereas 'will' belongs to:", "The Legislature.", "The Executive.", "The States.", "The People."],
  [7, "Which Anti-Federalist concern was Hamilton directly attempting to address in Federalist 78?", "The fear that unelected, life-tenured judges would destroy state courts and become tyrannical.", "The fear that the President would veto all laws.", "The fear that Congress would refuse to pass a budget.", "The fear that the military would be disbanded."],

  // --- DOC 8: The Constitution & Amendments ---
  [8, "Article I of the Constitution outlines the powers of which branch?", "The Legislative Branch", "The Executive Branch", "The Judicial Branch", "The States"],
  [8, "The 'Necessary and Proper Clause' (Elastic Clause) in Article I, Section 8 allows Congress to:", "Make laws required to carry out its enumerated powers.", "Veto decisions made by the Supreme Court.", "Appoint state governors.", "Suspend the Constitution during wartime."],
  [8, "Article II of the Constitution establishes the powers of:", "The President (Executive Branch).", "The Supreme Court.", "The Senate.", "The Electoral College."],
  [8, "The Supremacy Clause in Article VI establishes that:", "The Constitution and federal laws are the supreme law of the land.", "The President is supreme over Congress.", "State laws always override federal laws.", "The Supreme Court can rewrite the Constitution."],
  [8, "Which amendment protects the freedom of speech, religion, press, assembly, and petition?", "The 1st Amendment", "The 2nd Amendment", "The 4th Amendment", "The 10th Amendment"],
  [8, "The 10th Amendment is often cited to support the concept of federalism because it:", "Reserves all powers not delegated to the federal government to the states or the people.", "Abolished the electoral college.", "Gives Congress the power to regulate interstate commerce.", "Allows the President to deploy the national guard."],
  [8, "Which clause in the 14th Amendment has been used to apply the Bill of Rights to the states (Selective Incorporation)?", "The Due Process Clause", "The Equal Protection Clause", "The Commerce Clause", "The Citizenship Clause"],
  [8, "The Equal Protection Clause of the 14th Amendment was heavily relied upon in which landmark Supreme Court case?", "Brown v. Board of Education", "Marbury v. Madison", "McCulloch v. Maryland", "Citizens United v. FEC"],
  [8, "Article III of the Constitution is surprisingly brief and only explicitly creates:", "One Supreme Court, leaving the creation of lower courts to Congress.", "A massive network of 50 federal district courts.", "The Department of Justice.", "The power of Judicial Review."],
  [8, "The formal amendment process (Article V) reflects federalism because it requires:", "Proposal at the national level (Congress) and ratification at the state level.", "Approval by both the President and the Supreme Court.", "A unanimous vote by all citizens.", "A simple majority vote in both houses of Congress."],
  [8, "The Commerce Clause (Article I, Section 8) has been used historically to:", "Vastly expand the power of the federal government to regulate the economy.", "Strictly limit federal power over the states.", "Protect the institution of slavery.", "Prevent the creation of a national bank."],
  [8, "Which amendment protects citizens from unreasonable searches and seizures?", "The 4th Amendment", "The 5th Amendment", "The 8th Amendment", "The 1st Amendment"],
  [8, "The 'Three-Fifths Compromise' (later voided by the 13th and 14th amendments) originally determined:", "How enslaved people would be counted for representation and taxation.", "The ratio of states needed to ratify a treaty.", "The proportion of taxes that would go to the military.", "The voting rights of non-property owning males."],
  [8, "The 15th, 19th, 24th, and 26th Amendments all share what common goal?", "Expanding the right to vote (suffrage) to disenfranchised groups.", "Limiting the power of the President.", "Protecting the rights of the accused in court.", "Establishing limits on campaign finance."],
  [8, "According to Article I, who holds the sole power of Impeachment (bringing charges)?", "The House of Representatives", "The Senate", "The Supreme Court", "The Attorney General"],

  // --- DOC 9: Letter from Birmingham Jail ---
  [9, "Who is the author of the 'Letter from Birmingham Jail'?", "Dr. Martin Luther King Jr.", "Malcolm X", "Thurgood Marshall", "Rosa Parks"],
  [9, "Dr. King wrote the letter in response to a public statement made by:", "Eight white Southern clergymen who criticized his methods as 'unwise and untimely'.", "The Governor of Alabama.", "The President of the United States.", "The Chief of Police in Birmingham."],
  [9, "What are the four basic steps of a nonviolent campaign outlined by King?", "Collection of facts, negotiation, self-purification, and direct action.", "Protest, boycott, riot, and revolution.", "Petitioning, lobbying, voting, and appealing to courts.", "Ignoring the law, hiding, fleeing, and fighting back."],
  [9, "King justifies his presence in Birmingham by stating: 'Injustice anywhere is a threat to...'", "Justice everywhere.", "The American economy.", "The state's sovereignty.", "The local police force."],
  [9, "How does King distinguish between 'just' and 'unjust' laws?", "A just law uplifts human personality; an unjust law degrades human personality.", "A just law is passed by Congress; an unjust law is passed by states.", "A just law is easy to follow; an unjust law is too expensive.", "A just law applies to minorities; an unjust law applies to majorities."],
  [9, "King argues that an unjust law is a code that a numerical or power majority group compels a minority group to obey, but:", "Does not make binding on itself.", "Provides financial compensation for.", "Allows the minority to vote on.", "Is strictly enforced by the military."],
  [9, "According to King, one who breaks an unjust law must do so:", "Openly, lovingly, and with a willingness to accept the penalty.", "Secretly, violently, and aggressively.", "Only when no police officers are watching.", "With the intent to overthrow the entire government."],
  [9, "Who does King express his deep disappointment in, arguably more than the Ku Klux Klan?", "The white moderate, who prefers 'order' to justice.", "The federal government.", "The Supreme Court.", "Northern civil rights activists."],
  [9, "King uses the historical example of the Boston Tea Party to demonstrate that:", "Civil disobedience has a long, respected history in America.", "Taxes are inherently unjust.", "Violence is sometimes necessary to achieve goals.", "The British were entirely at fault for the Revolution."],
  [9, "Why does King argue that 'wait' has almost always meant 'never' for African Americans?", "Because privileged groups rarely give up their privileges voluntarily.", "Because the court system was moving too quickly.", "Because the federal government promised immediate action.", "Because the economic situation was improving naturally."],
  [9, "King responds to the accusation of being an 'extremist' by:", "Embracing the label, comparing himself to extremists for love like Jesus and Lincoln.", "Apologizing and promising to tone down his rhetoric.", "Accusing the clergymen of being the real extremists.", "Denying it and blaming his followers for the disruption."],
  [9, "The primary purpose of direct action (like sit-ins and marches), according to King, is to:", "Create a crisis and foster tension that forces a community to negotiate.", "Physically defeat the local police force.", "Bankrupt local businesses permanently.", "Gain media fame and personal wealth."],
  [9, "King references St. Thomas Aquinas and St. Augustine to provide a philosophical and theological basis for:", "The moral obligation to disobey unjust laws.", "The necessity of the separation of church and state.", "The absolute superiority of the federal government over states.", "The right to bear arms in self-defense."],
  [9, "What is King's view on the 'myth of time'?", "He rejects the idea that time inevitably cures all ills, stating time is neutral and must be used creatively.", "He believes that if they just wait 10 more years, segregation will end naturally.", "He believes the civil rights movement is moving far too fast.", "He argues that time travel is the only solution to racism."],
  [9, "In the conclusion of the letter, King expresses hope that:", "The dark clouds of racial prejudice will soon pass away, bringing love and brotherhood.", "The South will secede from the Union again.", "The white clergymen will be removed from their churches.", "The federal government will impose martial law in Alabama."]
];
